networks:
  membuss-net:
    driver: bridge

volumes:
  membuss-data-1:
  membuss-data-2:
  membuss-data-3:

services:
  membuss-1:
    image: membuss:local
    container_name: membuss-1
    entrypoint: ["/usr/local/bin/membuss-entrypoint"]
    command: ["/usr/local/bin/membuss", "-datadir", "/data/membuss"]
    environment:
      MEMBUSS_LISTEN_ADDRS: /ip4/0.0.0.0/tcp/4001,/ip4/0.0.0.0/udp/5001/quic-v1
      MEMBUSS_GATEWAY_ADDR: "0.0.0.0:8080"
      MEMBUSS_API_ADDR: "0.0.0.0:5001"
      MEMBUSS_GRPC_ADDR: "0.0.0.0:50051"
      MEMBUSS_DATA_DIR: /data/membuss
      MEMBUSS_ANCHOR_MODE: "true"
      MEMBUSS_MDNS: "true"
      MEMBUSS_DHT_MODE: server
      MEMBUSS_ENABLE_GEOLOCATION: "true"
    volumes:
      - membuss-data-1:/data/membuss
    ports:
      - "14001:4001"
      - "15001:5001"
      - "18080:8080"
      - "15051:50051"
    networks:
      - membuss-net

  membuss-2:
    image: membuss:local
    container_name: membuss-2
    entrypoint: ["/usr/local/bin/membuss-entrypoint"]
    command: ["/usr/local/bin/membuss", "-datadir", "/data/membuss"]
    environment:
      MEMBUSS_LISTEN_ADDRS: /ip4/0.0.0.0/tcp/4001,/ip4/0.0.0.0/udp/5001/quic-v1
      MEMBUSS_GATEWAY_ADDR: "0.0.0.0:8080"
      MEMBUSS_API_ADDR: "0.0.0.0:5001"
      MEMBUSS_GRPC_ADDR: "0.0.0.0:50051"
      MEMBUSS_DATA_DIR: /data/membuss
      MEMBUSS_ANCHOR_MODE: "false"
      MEMBUSS_AUTO_GC_INTERVAL: 2m
      MEMBUSS_GC_MIN_AGE: 24h
      MEMBUSS_MDNS: "true"
      MEMBUSS_DHT_MODE: server
      MEMBUSS_ENABLE_GEOLOCATION: "true"
    volumes:
      - membuss-data-2:/data/membuss
    ports:
      - "14002:4001"
      - "15002:5001"
      - "18081:8080"
      - "15052:50051"
    networks:
      - membuss-net
    depends_on:
      - membuss-1

  membuss-3:
    image: membuss:local
    container_name: membuss-3
    entrypoint: ["/usr/local/bin/membuss-entrypoint"]
    command: ["/usr/local/bin/membuss", "-datadir", "/data/membuss"]
    environment:
      MEMBUSS_LISTEN_ADDRS: /ip4/0.0.0.0/tcp/4001,/ip4/0.0.0.0/udp/5001/quic-v1
      MEMBUSS_GATEWAY_ADDR: "0.0.0.0:8080"
      MEMBUSS_API_ADDR: "0.0.0.0:5001"
      MEMBUSS_GRPC_ADDR: "0.0.0.0:50051"
      MEMBUSS_DATA_DIR: /data/membuss
      MEMBUSS_ANCHOR_MODE: "false"
      MEMBUSS_AUTO_GC_INTERVAL: 2m
      MEMBUSS_GC_MIN_AGE: 24h
      MEMBUSS_MDNS: "true"
      MEMBUSS_DHT_MODE: server
      MEMBUSS_ENABLE_GEOLOCATION: "true"
    volumes:
      - membuss-data-3:/data/membuss
    ports:
      - "14003:4001"
      - "15003:5001"
      - "18082:8080"
      - "15053:50051"
    networks:
      - membuss-net
    depends_on:
      - membuss-1
