package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// configTemplate is the YAML-with-comments source of truth for
// `membuss-cli init`. It is a hand-written YAML document with
// a small set of `<<PLACEHOLDER>>` markers (no Go text/template
// directives) so the .go file is readable and the template can
// be round-tripped through yaml.Unmarshal without escaping the
// brace-only placeholders that template syntax would require.
//
// The list fields (listen_addrs, bootstrap_peers) are appended
// programmatically by writeTemplate after the static body.
const configTemplate = `# Membuss Node Configuration
# Generated by: membuss-cli init
# This file is the single source of truth for the local node.
# Run `+"`membuss-cli init --force`"+` to regenerate it.

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------

# Data directory (can be overridden with --datadir flag or
# MEMBUSS_DATADIR env var).
data_dir: <<DATA_DIR>>

# Directory under data_dir that holds BadgerDB files.
datastore_subdir: datastore

# Directory under data_dir that holds membuss.log when log_file
# is not set to an absolute path.
logs_subdir: logs

# -----------------------------------------------------------------------------
# Networking
# -----------------------------------------------------------------------------

# libp2p multiaddrs the host binds to. TCP + QUIC are both
# exposed so peers can choose the cheaper transport.
listen_addrs:
<<LISTEN_ADDRS>>

# libp2p peer IDs (as multiaddrs) the DHT tries to connect to
# on startup. Leave empty for a fresh testnet or a single-node
# run; add full /ip4/.../p2p/<id> strings for known nodes.
bootstrap_peers:
<<BOOTSTRAP_PEERS>>

# gRPC listen address for the CLI <-> daemon transport.
grpc_addr: <<GRPC_ADDR>>

# Node control API listen address (HTTP).
api_addr: <<API_ADDR>>

# Public Mem-Gate HTTP gateway listen address.
gateway_addr: <<GATEWAY_ADDR>>

# -----------------------------------------------------------------------------
# Anchor / Relay
# -----------------------------------------------------------------------------

# When true, the Anchor Node full-sync engine mirrors all
# announced content so it stays available when original
# providers go offline.
anchor_mode: <<ANCHOR_MODE>>

# Circuit v2 relay. Anchor nodes should set this to true so
# they can forward traffic for NATed peers.
relay_service: <<RELAY_SERVICE>>
relay_max_conns: <<RELAY_MAX_CONNS>>
relay_max_reservations: <<RELAY_MAX_RESERVATIONS>>
relay_bandwidth_mb: <<RELAY_BANDWIDTH_MB>>
force_relay: <<FORCE_RELAY>>
nat_wait_seconds: <<NAT_WAIT_SECONDS>>

# -----------------------------------------------------------------------------
# Reprovide (Mem-Herald)
# -----------------------------------------------------------------------------

# How often Mem-Herald re-announces this node's provider
# records to the DHT.
reprovide_interval: <<REPROVIDE_INTERVAL>>

# Reprovide strategy. "roots" only re-pins DAG roots; "all"
# re-pins every sealed block; "shards" re-pins erasure shards.
# Allowed: roots | all | shards
reprovide_strategy: roots

# -----------------------------------------------------------------------------
# Erasure coding
# -----------------------------------------------------------------------------

erasure_data_shards:   10
erasure_parity_shards: 4

# -----------------------------------------------------------------------------
# Bloom filter (Phase 13)
# -----------------------------------------------------------------------------

# Expected number of MIDs the in-memory block-existence filter
# will hold. Tune to your expected block count for an optimal
# false-positive / memory trade-off.
bloom_capacity: <<BLOOM_CAPACITY>>
# Target false-positive rate. 0.001 = 0.1%.
bloom_fp_rate: <<BLOOM_FP_RATE>>
# Set to true to disable the bloom filter entirely (only do
# this on small test stores).
bloom_disabled: <<BLOOM_DISABLED>>
# How often the local node broadcasts its sealed-MID bloom
# filter to directly connected peers. 0 disables the gossip.
memex_bloom_announce_interval: <<MEMEX_BLOOM_ANNOUNCE_INTERVAL>>

# -----------------------------------------------------------------------------
# Chunking
# -----------------------------------------------------------------------------

# Allowed: fixed | rabin
chunk_strategy: fixed
chunk_size_kb:  256

# -----------------------------------------------------------------------------
# Networking knobs
# -----------------------------------------------------------------------------

memex_retry_backoff:
  initial:      100ms
  max:          30s
  factor:       2.0
  max_attempts: 4

bootstrap_backoff:
  initial:      500ms
  max:          60s
  factor:       2.0
  max_attempts: 0

gateway_rate_limit_per_min: 100

# -----------------------------------------------------------------------------
# API + observability
# -----------------------------------------------------------------------------

# Bearer key for the Node API and the Mem-Gate gateway. Empty
# disables auth (do not run that way in production).
api_key: <<API_KEY>>

gateway_tls:
  cert_file: ""
  key_file:  ""

api_tls:
  cert_file: ""
  key_file:  ""

# Prometheus /metrics endpoint. Set to false to disable.
metrics_enabled: <<METRICS_ENABLED>>

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

# Allowed: debug | info | warn | error
log_level: <<LOG_LEVEL>>

# Path to a log file. Empty = stdout. If a relative path is
# given it is resolved relative to data_dir/logs_subdir.
log_file: ""

# -----------------------------------------------------------------------------
# MID format
# -----------------------------------------------------------------------------

# Allowed: v1 | legacy
# v1 is the canonical CIDv1 + base32lower form. legacy is the
# pre-Phase-14 base58 form, supported for one release cycle so
# operators can drain pre-upgrade stores.
mid_version: <<MID_VERSION>>
`

// writeTemplate returns the rendered YAML-with-comments that
// `membuss-cli init` writes to disk. The result is stable for
// a given Config so two consecutive `init --force` calls
// produce byte-equal output (modulo the new identity.key).
func writeTemplate(cfg *Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config: nil")
	}

	listenBlock := ""
	for _, a := range cfg.ListenAddrs {
		listenBlock += "  - " + a + "\n"
	}
	bootBlock := ""
	for _, p := range cfg.BootstrapPeers {
		bootBlock += "  - " + p + "\n"
	}

	r := strings.NewReplacer(
		"<<DATA_DIR>>",                     cfg.DataDir,
		"<<GRPC_ADDR>>",                    cfg.GRPCAddr,
		"<<API_ADDR>>",                     cfg.APIAddr,
		"<<GATEWAY_ADDR>>",                 cfg.GatewayAddr,
		"<<ANCHOR_MODE>>",                  boolString(cfg.AnchorMode),
		"<<RELAY_SERVICE>>",                boolString(cfg.RelayService),
		"<<RELAY_MAX_CONNS>>",              intString(cfg.RelayMaxConns),
		"<<RELAY_MAX_RESERVATIONS>>",       intString(cfg.RelayMaxReservations),
		"<<RELAY_BANDWIDTH_MB>>",           intString(cfg.RelayBandwidthMB),
		"<<FORCE_RELAY>>",                  boolString(cfg.ForceRelay),
		"<<NAT_WAIT_SECONDS>>",             intString(cfg.NATWaitSeconds),
		"<<REPROVIDE_INTERVAL>>",           durationString(cfg.ReprovideInterval),
		"<<BLOOM_CAPACITY>>",               uintString(cfg.BloomCapacity),
		"<<BLOOM_FP_RATE>>",                fpFormatter(cfg.BloomFPRate),
		"<<BLOOM_DISABLED>>",               boolString(cfg.BloomDisabled),
		"<<MEMEX_BLOOM_ANNOUNCE_INTERVAL>>", durationString(cfg.MemexBloomAnnounceInterval),
		"<<API_KEY>>",                      cfg.APIKey,
		"<<METRICS_ENABLED>>",              boolString(cfg.MetricsEnabled),
		"<<LOG_LEVEL>>",                    cfg.LogLevel,
		"<<MID_VERSION>>",                  cfg.MIDVersion,
		"<<LISTEN_ADDRS>>",                 listenBlock,
		"<<BOOTSTRAP_PEERS>>",              bootBlock,
	)
	return r.Replace(configTemplate), nil
}

// fpFormatter renders a float the same way the rest of the
// file expects it ("0.001"), trimming trailing zeros so the
// output stays tidy.
func fpFormatter(fp float64) string {
	s := strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", fp), "0"), ".")
	if s == "" {
		return "0"
	}
	return s
}

// WriteConfig renders cfg to a YAML-with-comments file at path.
// The destination is created with 0600 permissions so that an
// accidental world-readable config (which can carry the API
// key) is harder to misconfigure. The parent directory is
// expected to exist; WriteConfig does NOT mkdir it.
func WriteConfig(cfg *Config, path string) error {
	if cfg == nil {
		return fmt.Errorf("config: nil")
	}
	if path == "" {
		return fmt.Errorf("config: empty path")
	}
	rendered, err := writeTemplate(cfg)
	if err != nil {
		return err
	}
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("config: mkdir %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, []byte(rendered), 0o600); err != nil {
		return fmt.Errorf("config: write %s: %w", path, err)
	}
	return nil
}

// --- small string formatters used by the template ---

func boolString(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func intString(i int) string {
	return fmt.Sprintf("%d", i)
}

func uintString(u uint) string {
	return fmt.Sprintf("%d", u)
}

// durationString renders a time.Duration in the same form Go's
// yaml.v3 uses by default ("12h0m0s") so the file is round-
// trip safe through Load.
func durationString(d time.Duration) string {
	if d == 0 {
		return "0s"
	}
	return d.String()
}
