// Phase 1 wire schema for the CLI <-> daemon gRPC service and the
// core content-addressed primitives.
//
// Real RPCs (Add, Seal, Resolve, Provide, etc.) are added in later
// phases. This file exists so that the codegen pipeline and the
// go_package layout are exercised end-to-end from day one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: membuss.proto

package membusspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional caller-supplied message echoed back in the response.
	// Useful for round-trip checks.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_membuss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The echoed message (empty if the request had none).
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The daemon's build identifier (set at compile time).
	Build         string `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_membuss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

// Block is a single chunk of content, addressed by its MID.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bytes of the chunk.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// MID of this block (mem-prefixed multibase multihash string).
	Mid string `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	// Size in bytes of the data payload.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_membuss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Block) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DAGNode is one node in a Merkle DAG.
//
// Leaf nodes carry inline `data` and have empty `links`. Internal
// nodes carry only `links` to their child MIDs. The `mid` field is
// the MID of this node (derived from `links` and `data`).
type DAGNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MIDs of the children of this node, in order.
	Links []string `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	// Inline data for leaf nodes; empty for internal nodes.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// MID of this node (mem-prefixed multibase multihash string).
	Mid           string `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGNode) Reset() {
	*x = DAGNode{}
	mi := &file_membuss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGNode) ProtoMessage() {}

func (x *DAGNode) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGNode.ProtoReflect.Descriptor instead.
func (*DAGNode) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{3}
}

func (x *DAGNode) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *DAGNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DAGNode) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

var File_membuss_proto protoreflect.FileDescriptor

const file_membuss_proto_rawDesc = "" +
	"\n" +
	"\rmembuss.proto\x12\n" +
	"membuss.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\"A\n" +
	"\x05Block\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\tR\x03mid\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"E\n" +
	"\aDAGNode\x12\x14\n" +
	"\x05links\x18\x01 \x03(\tR\x05links\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\tR\x03mid2A\n" +
	"\x04Node\x129\n" +
	"\x04Ping\x12\x17.membuss.v1.PingRequest\x1a\x18.membuss.v1.PingResponseB.Z,github.com/nnlgsakib/membuss/proto;membusspbb\x06proto3"

var (
	file_membuss_proto_rawDescOnce sync.Once
	file_membuss_proto_rawDescData []byte
)

func file_membuss_proto_rawDescGZIP() []byte {
	file_membuss_proto_rawDescOnce.Do(func() {
		file_membuss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membuss_proto_rawDesc), len(file_membuss_proto_rawDesc)))
	})
	return file_membuss_proto_rawDescData
}

var file_membuss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_membuss_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: membuss.v1.PingRequest
	(*PingResponse)(nil), // 1: membuss.v1.PingResponse
	(*Block)(nil),        // 2: membuss.v1.Block
	(*DAGNode)(nil),      // 3: membuss.v1.DAGNode
}
var file_membuss_proto_depIdxs = []int32{
	0, // 0: membuss.v1.Node.Ping:input_type -> membuss.v1.PingRequest
	1, // 1: membuss.v1.Node.Ping:output_type -> membuss.v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_membuss_proto_init() }
func file_membuss_proto_init() {
	if File_membuss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membuss_proto_rawDesc), len(file_membuss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membuss_proto_goTypes,
		DependencyIndexes: file_membuss_proto_depIdxs,
		MessageInfos:      file_membuss_proto_msgTypes,
	}.Build()
	File_membuss_proto = out.File
	file_membuss_proto_goTypes = nil
	file_membuss_proto_depIdxs = nil
}
