// Wire schema for the Membuss libp2p protocols (PEX, Memex) and
// the CLI <-> daemon gRPC service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: membuss.proto

package membusspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reachability describes how a peer is reachable from a remote
// node. Used by PEX to decide which addresses are worth sharing
// in a gossip round (Phase 12).
type Reachability int32

const (
	Reachability_UNKNOWN    Reachability = 0
	Reachability_PUBLIC     Reachability = 1
	Reachability_PRIVATE    Reachability = 2
	Reachability_RELAY_ONLY Reachability = 3
)

// Enum value maps for Reachability.
var (
	Reachability_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUBLIC",
		2: "PRIVATE",
		3: "RELAY_ONLY",
	}
	Reachability_value = map[string]int32{
		"UNKNOWN":    0,
		"PUBLIC":     1,
		"PRIVATE":    2,
		"RELAY_ONLY": 3,
	}
)

func (x Reachability) Enum() *Reachability {
	p := new(Reachability)
	*p = x
	return p
}

func (x Reachability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reachability) Descriptor() protoreflect.EnumDescriptor {
	return file_membuss_proto_enumTypes[0].Descriptor()
}

func (Reachability) Type() protoreflect.EnumType {
	return &file_membuss_proto_enumTypes[0]
}

func (x Reachability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reachability.Descriptor instead.
func (Reachability) EnumDescriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_membuss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Build         string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_membuss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Chunker       string                 `protobuf:"bytes,2,opt,name=chunker,proto3" json:"chunker,omitempty"`
	ChunkSize     uint32                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	NoSeal        bool                   `protobuf:"varint,4,opt,name=no_seal,json=noSeal,proto3" json:"no_seal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_membuss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddRequest) GetChunker() string {
	if x != nil {
		return x.Chunker
	}
	return ""
}

func (x *AddRequest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *AddRequest) GetNoSeal() bool {
	if x != nil {
		return x.NoSeal
	}
	return false
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Blocks        uint64                 `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Sealed        bool                   `protobuf:"varint,4,opt,name=sealed,proto3" json:"sealed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_membuss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *AddResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AddResponse) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *AddResponse) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_membuss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *GetRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunk) Reset() {
	*x = GetChunk{}
	mi := &file_membuss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunk) ProtoMessage() {}

func (x *GetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunk.ProtoReflect.Descriptor instead.
func (*GetChunk) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{5}
}

func (x *GetChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetChunk) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	mi := &file_membuss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{6}
}

func (x *SealRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *SealRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type SealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pinned        uint64                 `protobuf:"varint,1,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Already       bool                   `protobuf:"varint,2,opt,name=already,proto3" json:"already,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	mi := &file_membuss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{7}
}

func (x *SealResponse) GetPinned() uint64 {
	if x != nil {
		return x.Pinned
	}
	return 0
}

func (x *SealResponse) GetAlready() bool {
	if x != nil {
		return x.Already
	}
	return false
}

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_membuss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{8}
}

func (x *UnsealRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       uint64                 `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_membuss_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{9}
}

func (x *UnsealResponse) GetRemoved() uint64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_membuss_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{10}
}

func (x *StatRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Blocks        uint64                 `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Sealed        bool                   `protobuf:"varint,4,opt,name=sealed,proto3" json:"sealed,omitempty"`
	Codec         uint64                 `protobuf:"varint,5,opt,name=codec,proto3" json:"codec,omitempty"`
	Erasure       *ErasureInfo           `protobuf:"bytes,6,opt,name=erasure,proto3" json:"erasure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_membuss_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponse) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *StatResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *StatResponse) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

func (x *StatResponse) GetCodec() uint64 {
	if x != nil {
		return x.Codec
	}
	return 0
}

func (x *StatResponse) GetErasure() *ErasureInfo {
	if x != nil {
		return x.Erasure
	}
	return nil
}

type ErasureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataShards    uint32                 `protobuf:"varint,1,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards  uint32                 `protobuf:"varint,2,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	ShardMids     []string               `protobuf:"bytes,3,rep,name=shard_mids,json=shardMids,proto3" json:"shard_mids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErasureInfo) Reset() {
	*x = ErasureInfo{}
	mi := &file_membuss_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErasureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErasureInfo) ProtoMessage() {}

func (x *ErasureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErasureInfo.ProtoReflect.Descriptor instead.
func (*ErasureInfo) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{12}
}

func (x *ErasureInfo) GetDataShards() uint32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *ErasureInfo) GetParityShards() uint32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

func (x *ErasureInfo) GetShardMids() []string {
	if x != nil {
		return x.ShardMids
	}
	return nil
}

// NodePeerInfo is the gRPC-facing peer descriptor used by the
// Peers and DHTPeek RPCs. The libp2p wire-level PeerInfo (used
// by PEX) is defined further below.
type NodePeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePeerInfo) Reset() {
	*x = NodePeerInfo{}
	mi := &file_membuss_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePeerInfo) ProtoMessage() {}

func (x *NodePeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePeerInfo.ProtoReflect.Descriptor instead.
func (*NodePeerInfo) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{13}
}

func (x *NodePeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NodePeerInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type PeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersRequest) Reset() {
	*x = PeersRequest{}
	mi := &file_membuss_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersRequest) ProtoMessage() {}

func (x *PeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersRequest.ProtoReflect.Descriptor instead.
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{14}
}

func (x *PeersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodePeerInfo        `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponse) Reset() {
	*x = PeersResponse{}
	mi := &file_membuss_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse) ProtoMessage() {}

func (x *PeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse.ProtoReflect.Descriptor instead.
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{15}
}

func (x *PeersResponse) GetPeers() []*NodePeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeersResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DHTPeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHTPeekRequest) Reset() {
	*x = DHTPeekRequest{}
	mi := &file_membuss_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHTPeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTPeekRequest) ProtoMessage() {}

func (x *DHTPeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTPeekRequest.ProtoReflect.Descriptor instead.
func (*DHTPeekRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{16}
}

func (x *DHTPeekRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *DHTPeekRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DHTPeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*NodePeerInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHTPeekResponse) Reset() {
	*x = DHTPeekResponse{}
	mi := &file_membuss_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHTPeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTPeekResponse) ProtoMessage() {}

func (x *DHTPeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTPeekResponse.ProtoReflect.Descriptor instead.
func (*DHTPeekResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{17}
}

func (x *DHTPeekResponse) GetProviders() []*NodePeerInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCRequest) Reset() {
	*x = GCRequest{}
	mi := &file_membuss_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCRequest) ProtoMessage() {}

func (x *GCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCRequest.ProtoReflect.Descriptor instead.
func (*GCRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{18}
}

func (x *GCRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesFreed    uint64                 `protobuf:"varint,1,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	BlocksKept    uint64                 `protobuf:"varint,2,opt,name=blocks_kept,json=blocksKept,proto3" json:"blocks_kept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCResponse) Reset() {
	*x = GCResponse{}
	mi := &file_membuss_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCResponse) ProtoMessage() {}

func (x *GCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCResponse.ProtoReflect.Descriptor instead.
func (*GCResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{19}
}

func (x *GCResponse) GetBytesFreed() uint64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

func (x *GCResponse) GetBlocksKept() uint64 {
	if x != nil {
		return x.BlocksKept
	}
	return 0
}

type AnchorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorStatusRequest) Reset() {
	*x = AnchorStatusRequest{}
	mi := &file_membuss_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorStatusRequest) ProtoMessage() {}

func (x *AnchorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorStatusRequest.ProtoReflect.Descriptor instead.
func (*AnchorStatusRequest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{20}
}

type AnchorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	BlocksHeld    int64                  `protobuf:"varint,3,opt,name=blocks_held,json=blocksHeld,proto3" json:"blocks_held,omitempty"`
	Anchors       int32                  `protobuf:"varint,4,opt,name=anchors,proto3" json:"anchors,omitempty"`
	Backlog       int32                  `protobuf:"varint,5,opt,name=backlog,proto3" json:"backlog,omitempty"`
	Synced        int64                  `protobuf:"varint,6,opt,name=synced,proto3" json:"synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorStatusResponse) Reset() {
	*x = AnchorStatusResponse{}
	mi := &file_membuss_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorStatusResponse) ProtoMessage() {}

func (x *AnchorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorStatusResponse.ProtoReflect.Descriptor instead.
func (*AnchorStatusResponse) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{21}
}

func (x *AnchorStatusResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AnchorStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AnchorStatusResponse) GetBlocksHeld() int64 {
	if x != nil {
		return x.BlocksHeld
	}
	return 0
}

func (x *AnchorStatusResponse) GetAnchors() int32 {
	if x != nil {
		return x.Anchors
	}
	return 0
}

func (x *AnchorStatusResponse) GetBacklog() int32 {
	if x != nil {
		return x.Backlog
	}
	return 0
}

func (x *AnchorStatusResponse) GetSynced() int64 {
	if x != nil {
		return x.Synced
	}
	return 0
}

// Block is a single chunk of content, addressed by its MID.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Mid           string                 `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_membuss_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{22}
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Block) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DAGNode is one node in a Merkle DAG.
type DAGNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []string               `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Mid           string                 `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGNode) Reset() {
	*x = DAGNode{}
	mi := &file_membuss_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGNode) ProtoMessage() {}

func (x *DAGNode) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGNode.ProtoReflect.Descriptor instead.
func (*DAGNode) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{23}
}

func (x *DAGNode) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *DAGNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DAGNode) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

// Shard is one erasure-coded shard of a block.
type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Mid           string                 `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	OriginalMid   string                 `protobuf:"bytes,4,opt,name=original_mid,json=originalMid,proto3" json:"original_mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_membuss_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{24}
}

func (x *Shard) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Shard) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Shard) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Shard) GetOriginalMid() string {
	if x != nil {
		return x.OriginalMid
	}
	return ""
}

// ErasureManifest is stored under the original block's MID.
type ErasureManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalMid   string                 `protobuf:"bytes,1,opt,name=original_mid,json=originalMid,proto3" json:"original_mid,omitempty"`
	DataShards    uint32                 `protobuf:"varint,2,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards  uint32                 `protobuf:"varint,3,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	ShardMids     []string               `protobuf:"bytes,4,rep,name=shard_mids,json=shardMids,proto3" json:"shard_mids,omitempty"`
	OriginalSize  uint64                 `protobuf:"varint,5,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErasureManifest) Reset() {
	*x = ErasureManifest{}
	mi := &file_membuss_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErasureManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErasureManifest) ProtoMessage() {}

func (x *ErasureManifest) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErasureManifest.ProtoReflect.Descriptor instead.
func (*ErasureManifest) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{25}
}

func (x *ErasureManifest) GetOriginalMid() string {
	if x != nil {
		return x.OriginalMid
	}
	return ""
}

func (x *ErasureManifest) GetDataShards() uint32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *ErasureManifest) GetParityShards() uint32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

func (x *ErasureManifest) GetShardMids() []string {
	if x != nil {
		return x.ShardMids
	}
	return nil
}

func (x *ErasureManifest) GetOriginalSize() uint64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

// PeerInfo is one entry in a PEX gossip payload. The libp2p
// wire format was extended in Phase 12 with relay_addrs,
// reachability and last_dial_success; the field tags are kept
// compatible with the old shape (1=peer_id, 2=addrs, 3=last_seen)
// so older nodes can still parse the message (the new fields
// are simply ignored).
type PeerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs           []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	RelayAddrs      []string               `protobuf:"bytes,3,rep,name=relay_addrs,json=relayAddrs,proto3" json:"relay_addrs,omitempty"` // Phase 12
	LastSeen        int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Reachability    Reachability           `protobuf:"varint,5,opt,name=reachability,proto3,enum=membuss.v1.Reachability" json:"reachability,omitempty"`   // Phase 12
	LastDialSuccess bool                   `protobuf:"varint,6,opt,name=last_dial_success,json=lastDialSuccess,proto3" json:"last_dial_success,omitempty"` // Phase 12
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_membuss_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{26}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PeerInfo) GetRelayAddrs() []string {
	if x != nil {
		return x.RelayAddrs
	}
	return nil
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetReachability() Reachability {
	if x != nil {
		return x.Reachability
	}
	return Reachability_UNKNOWN
}

func (x *PeerInfo) GetLastDialSuccess() bool {
	if x != nil {
		return x.LastDialSuccess
	}
	return false
}

// PEXMessage is the body of a /membuss/pex/1.0.0 gossip frame.
type PEXMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEXMessage) Reset() {
	*x = PEXMessage{}
	mi := &file_membuss_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEXMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEXMessage) ProtoMessage() {}

func (x *PEXMessage) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEXMessage.ProtoReflect.Descriptor instead.
func (*PEXMessage) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{27}
}

func (x *PEXMessage) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// WantEntry is one entry in a Memex want list.
type WantEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	SendDontHave  bool                   `protobuf:"varint,3,opt,name=send_dont_have,json=sendDontHave,proto3" json:"send_dont_have,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantEntry) Reset() {
	*x = WantEntry{}
	mi := &file_membuss_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantEntry) ProtoMessage() {}

func (x *WantEntry) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantEntry.ProtoReflect.Descriptor instead.
func (*WantEntry) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{28}
}

func (x *WantEntry) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *WantEntry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WantEntry) GetSendDontHave() bool {
	if x != nil {
		return x.SendDontHave
	}
	return false
}

// MemexMessage is the body of a /membuss/memex/1.0.0 frame.
type MemexMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wants         []*WantEntry           `protobuf:"bytes,1,rep,name=wants,proto3" json:"wants,omitempty"`
	Blocks        []*Block               `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	HaveMids      []string               `protobuf:"bytes,3,rep,name=have_mids,json=haveMids,proto3" json:"have_mids,omitempty"`
	Cancel        []string               `protobuf:"bytes,4,rep,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemexMessage) Reset() {
	*x = MemexMessage{}
	mi := &file_membuss_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemexMessage) ProtoMessage() {}

func (x *MemexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemexMessage.ProtoReflect.Descriptor instead.
func (*MemexMessage) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{29}
}

func (x *MemexMessage) GetWants() []*WantEntry {
	if x != nil {
		return x.Wants
	}
	return nil
}

func (x *MemexMessage) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *MemexMessage) GetHaveMids() []string {
	if x != nil {
		return x.HaveMids
	}
	return nil
}

func (x *MemexMessage) GetCancel() []string {
	if x != nil {
		return x.Cancel
	}
	return nil
}

// BloomAnnouncement is the body of a /membuss/memex-bloom/1.0.0
// frame (Phase 13). Peers periodically broadcast the bloom
// filter of their sealed MID set so Memex sessions can avoid
// asking providers that are guaranteed not to have a block.
type BloomAnnouncement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BloomFilter   []byte                 `protobuf:"bytes,1,opt,name=bloom_filter,json=bloomFilter,proto3" json:"bloom_filter,omitempty"` // serialized bloom filter (MarshalBinary)
	ItemCount     uint64                 `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`      // approximate MIDs represented
	Capacity      uint64                 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`                         // configured capacity
	FpRate        float64                `protobuf:"fixed64,4,opt,name=fp_rate,json=fpRate,proto3" json:"fp_rate,omitempty"`              // configured false-positive rate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloomAnnouncement) Reset() {
	*x = BloomAnnouncement{}
	mi := &file_membuss_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloomAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomAnnouncement) ProtoMessage() {}

func (x *BloomAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_membuss_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomAnnouncement.ProtoReflect.Descriptor instead.
func (*BloomAnnouncement) Descriptor() ([]byte, []int) {
	return file_membuss_proto_rawDescGZIP(), []int{30}
}

func (x *BloomAnnouncement) GetBloomFilter() []byte {
	if x != nil {
		return x.BloomFilter
	}
	return nil
}

func (x *BloomAnnouncement) GetItemCount() uint64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *BloomAnnouncement) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BloomAnnouncement) GetFpRate() float64 {
	if x != nil {
		return x.FpRate
	}
	return 0
}

var File_membuss_proto protoreflect.FileDescriptor

const file_membuss_proto_rawDesc = "" +
	"\n" +
	"\rmembuss.proto\x12\n" +
	"membuss.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\"r\n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\achunker\x18\x02 \x01(\tR\achunker\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\x12\x17\n" +
	"\ano_seal\x18\x04 \x01(\bR\x06noSeal\"c\n" +
	"\vAddResponse\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06blocks\x18\x03 \x01(\x04R\x06blocks\x12\x16\n" +
	"\x06sealed\x18\x04 \x01(\bR\x06sealed\"L\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"J\n" +
	"\bGetChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"=\n" +
	"\vSealRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"@\n" +
	"\fSealResponse\x12\x16\n" +
	"\x06pinned\x18\x01 \x01(\x04R\x06pinned\x12\x18\n" +
	"\aalready\x18\x02 \x01(\bR\aalready\"!\n" +
	"\rUnsealRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\"*\n" +
	"\x0eUnsealResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x04R\aremoved\"\x1f\n" +
	"\vStatRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\"\xb5\x01\n" +
	"\fStatResponse\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06blocks\x18\x03 \x01(\x04R\x06blocks\x12\x16\n" +
	"\x06sealed\x18\x04 \x01(\bR\x06sealed\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\x04R\x05codec\x121\n" +
	"\aerasure\x18\x06 \x01(\v2\x17.membuss.v1.ErasureInfoR\aerasure\"r\n" +
	"\vErasureInfo\x12\x1f\n" +
	"\vdata_shards\x18\x01 \x01(\rR\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\x02 \x01(\rR\fparityShards\x12\x1d\n" +
	"\n" +
	"shard_mids\x18\x03 \x03(\tR\tshardMids\"=\n" +
	"\fNodePeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"$\n" +
	"\fPeersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"U\n" +
	"\rPeersResponse\x12.\n" +
	"\x05peers\x18\x01 \x03(\v2\x18.membuss.v1.NodePeerInfoR\x05peers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"8\n" +
	"\x0eDHTPeekRequest\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"I\n" +
	"\x0fDHTPeekResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.membuss.v1.NodePeerInfoR\tproviders\"\x1d\n" +
	"\tGCRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"N\n" +
	"\n" +
	"GCResponse\x12\x1f\n" +
	"\vbytes_freed\x18\x01 \x01(\x04R\n" +
	"bytesFreed\x12\x1f\n" +
	"\vblocks_kept\x18\x02 \x01(\x04R\n" +
	"blocksKept\"\x15\n" +
	"\x13AnchorStatusRequest\"\xc3\x01\n" +
	"\x14AnchorStatusResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vblocks_held\x18\x03 \x01(\x03R\n" +
	"blocksHeld\x12\x18\n" +
	"\aanchors\x18\x04 \x01(\x05R\aanchors\x12\x18\n" +
	"\abacklog\x18\x05 \x01(\x05R\abacklog\x12\x16\n" +
	"\x06synced\x18\x06 \x01(\x03R\x06synced\"A\n" +
	"\x05Block\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\tR\x03mid\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"E\n" +
	"\aDAGNode\x12\x14\n" +
	"\x05links\x18\x01 \x03(\tR\x05links\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\tR\x03mid\"f\n" +
	"\x05Shard\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\tR\x03mid\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12!\n" +
	"\foriginal_mid\x18\x04 \x01(\tR\voriginalMid\"\xbe\x01\n" +
	"\x0fErasureManifest\x12!\n" +
	"\foriginal_mid\x18\x01 \x01(\tR\voriginalMid\x12\x1f\n" +
	"\vdata_shards\x18\x02 \x01(\rR\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\x03 \x01(\rR\fparityShards\x12\x1d\n" +
	"\n" +
	"shard_mids\x18\x04 \x03(\tR\tshardMids\x12#\n" +
	"\roriginal_size\x18\x05 \x01(\x04R\foriginalSize\"\xe1\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x1f\n" +
	"\vrelay_addrs\x18\x03 \x03(\tR\n" +
	"relayAddrs\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12<\n" +
	"\freachability\x18\x05 \x01(\x0e2\x18.membuss.v1.ReachabilityR\freachability\x12*\n" +
	"\x11last_dial_success\x18\x06 \x01(\bR\x0flastDialSuccess\"8\n" +
	"\n" +
	"PEXMessage\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.membuss.v1.PeerInfoR\x05peers\"_\n" +
	"\tWantEntry\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\tR\x03mid\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12$\n" +
	"\x0esend_dont_have\x18\x03 \x01(\bR\fsendDontHave\"\x9b\x01\n" +
	"\fMemexMessage\x12+\n" +
	"\x05wants\x18\x01 \x03(\v2\x15.membuss.v1.WantEntryR\x05wants\x12)\n" +
	"\x06blocks\x18\x02 \x03(\v2\x11.membuss.v1.BlockR\x06blocks\x12\x1b\n" +
	"\thave_mids\x18\x03 \x03(\tR\bhaveMids\x12\x16\n" +
	"\x06cancel\x18\x04 \x03(\tR\x06cancel\"\x8a\x01\n" +
	"\x11BloomAnnouncement\x12!\n" +
	"\fbloom_filter\x18\x01 \x01(\fR\vbloomFilter\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x04R\titemCount\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x04R\bcapacity\x12\x17\n" +
	"\afp_rate\x18\x04 \x01(\x01R\x06fpRate*D\n" +
	"\fReachability\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\v\n" +
	"\aPRIVATE\x10\x02\x12\x0e\n" +
	"\n" +
	"RELAY_ONLY\x10\x032A\n" +
	"\x04Node\x129\n" +
	"\x04Ping\x12\x17.membuss.v1.PingRequest\x1a\x18.membuss.v1.PingResponse2\xbd\x04\n" +
	"\vMembussNode\x126\n" +
	"\x03Add\x12\x16.membuss.v1.AddRequest\x1a\x17.membuss.v1.AddResponse\x125\n" +
	"\x03Get\x12\x16.membuss.v1.GetRequest\x1a\x14.membuss.v1.GetChunk0\x01\x129\n" +
	"\x04Seal\x12\x17.membuss.v1.SealRequest\x1a\x18.membuss.v1.SealResponse\x12?\n" +
	"\x06Unseal\x12\x19.membuss.v1.UnsealRequest\x1a\x1a.membuss.v1.UnsealResponse\x129\n" +
	"\x04Stat\x12\x17.membuss.v1.StatRequest\x1a\x18.membuss.v1.StatResponse\x12<\n" +
	"\x05Peers\x12\x18.membuss.v1.PeersRequest\x1a\x19.membuss.v1.PeersResponse\x12B\n" +
	"\aDHTPeek\x12\x1a.membuss.v1.DHTPeekRequest\x1a\x1b.membuss.v1.DHTPeekResponse\x123\n" +
	"\x02GC\x12\x15.membuss.v1.GCRequest\x1a\x16.membuss.v1.GCResponse\x12Q\n" +
	"\fAnchorStatus\x12\x1f.membuss.v1.AnchorStatusRequest\x1a .membuss.v1.AnchorStatusResponseB.Z,github.com/nnlgsakib/membuss/proto;membusspbb\x06proto3"

var (
	file_membuss_proto_rawDescOnce sync.Once
	file_membuss_proto_rawDescData []byte
)

func file_membuss_proto_rawDescGZIP() []byte {
	file_membuss_proto_rawDescOnce.Do(func() {
		file_membuss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membuss_proto_rawDesc), len(file_membuss_proto_rawDesc)))
	})
	return file_membuss_proto_rawDescData
}

var file_membuss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_membuss_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_membuss_proto_goTypes = []any{
	(Reachability)(0),            // 0: membuss.v1.Reachability
	(*PingRequest)(nil),          // 1: membuss.v1.PingRequest
	(*PingResponse)(nil),         // 2: membuss.v1.PingResponse
	(*AddRequest)(nil),           // 3: membuss.v1.AddRequest
	(*AddResponse)(nil),          // 4: membuss.v1.AddResponse
	(*GetRequest)(nil),           // 5: membuss.v1.GetRequest
	(*GetChunk)(nil),             // 6: membuss.v1.GetChunk
	(*SealRequest)(nil),          // 7: membuss.v1.SealRequest
	(*SealResponse)(nil),         // 8: membuss.v1.SealResponse
	(*UnsealRequest)(nil),        // 9: membuss.v1.UnsealRequest
	(*UnsealResponse)(nil),       // 10: membuss.v1.UnsealResponse
	(*StatRequest)(nil),          // 11: membuss.v1.StatRequest
	(*StatResponse)(nil),         // 12: membuss.v1.StatResponse
	(*ErasureInfo)(nil),          // 13: membuss.v1.ErasureInfo
	(*NodePeerInfo)(nil),         // 14: membuss.v1.NodePeerInfo
	(*PeersRequest)(nil),         // 15: membuss.v1.PeersRequest
	(*PeersResponse)(nil),        // 16: membuss.v1.PeersResponse
	(*DHTPeekRequest)(nil),       // 17: membuss.v1.DHTPeekRequest
	(*DHTPeekResponse)(nil),      // 18: membuss.v1.DHTPeekResponse
	(*GCRequest)(nil),            // 19: membuss.v1.GCRequest
	(*GCResponse)(nil),           // 20: membuss.v1.GCResponse
	(*AnchorStatusRequest)(nil),  // 21: membuss.v1.AnchorStatusRequest
	(*AnchorStatusResponse)(nil), // 22: membuss.v1.AnchorStatusResponse
	(*Block)(nil),                // 23: membuss.v1.Block
	(*DAGNode)(nil),              // 24: membuss.v1.DAGNode
	(*Shard)(nil),                // 25: membuss.v1.Shard
	(*ErasureManifest)(nil),      // 26: membuss.v1.ErasureManifest
	(*PeerInfo)(nil),             // 27: membuss.v1.PeerInfo
	(*PEXMessage)(nil),           // 28: membuss.v1.PEXMessage
	(*WantEntry)(nil),            // 29: membuss.v1.WantEntry
	(*MemexMessage)(nil),         // 30: membuss.v1.MemexMessage
	(*BloomAnnouncement)(nil),    // 31: membuss.v1.BloomAnnouncement
}
var file_membuss_proto_depIdxs = []int32{
	13, // 0: membuss.v1.StatResponse.erasure:type_name -> membuss.v1.ErasureInfo
	14, // 1: membuss.v1.PeersResponse.peers:type_name -> membuss.v1.NodePeerInfo
	14, // 2: membuss.v1.DHTPeekResponse.providers:type_name -> membuss.v1.NodePeerInfo
	0,  // 3: membuss.v1.PeerInfo.reachability:type_name -> membuss.v1.Reachability
	27, // 4: membuss.v1.PEXMessage.peers:type_name -> membuss.v1.PeerInfo
	29, // 5: membuss.v1.MemexMessage.wants:type_name -> membuss.v1.WantEntry
	23, // 6: membuss.v1.MemexMessage.blocks:type_name -> membuss.v1.Block
	1,  // 7: membuss.v1.Node.Ping:input_type -> membuss.v1.PingRequest
	3,  // 8: membuss.v1.MembussNode.Add:input_type -> membuss.v1.AddRequest
	5,  // 9: membuss.v1.MembussNode.Get:input_type -> membuss.v1.GetRequest
	7,  // 10: membuss.v1.MembussNode.Seal:input_type -> membuss.v1.SealRequest
	9,  // 11: membuss.v1.MembussNode.Unseal:input_type -> membuss.v1.UnsealRequest
	11, // 12: membuss.v1.MembussNode.Stat:input_type -> membuss.v1.StatRequest
	15, // 13: membuss.v1.MembussNode.Peers:input_type -> membuss.v1.PeersRequest
	17, // 14: membuss.v1.MembussNode.DHTPeek:input_type -> membuss.v1.DHTPeekRequest
	19, // 15: membuss.v1.MembussNode.GC:input_type -> membuss.v1.GCRequest
	21, // 16: membuss.v1.MembussNode.AnchorStatus:input_type -> membuss.v1.AnchorStatusRequest
	2,  // 17: membuss.v1.Node.Ping:output_type -> membuss.v1.PingResponse
	4,  // 18: membuss.v1.MembussNode.Add:output_type -> membuss.v1.AddResponse
	6,  // 19: membuss.v1.MembussNode.Get:output_type -> membuss.v1.GetChunk
	8,  // 20: membuss.v1.MembussNode.Seal:output_type -> membuss.v1.SealResponse
	10, // 21: membuss.v1.MembussNode.Unseal:output_type -> membuss.v1.UnsealResponse
	12, // 22: membuss.v1.MembussNode.Stat:output_type -> membuss.v1.StatResponse
	16, // 23: membuss.v1.MembussNode.Peers:output_type -> membuss.v1.PeersResponse
	18, // 24: membuss.v1.MembussNode.DHTPeek:output_type -> membuss.v1.DHTPeekResponse
	20, // 25: membuss.v1.MembussNode.GC:output_type -> membuss.v1.GCResponse
	22, // 26: membuss.v1.MembussNode.AnchorStatus:output_type -> membuss.v1.AnchorStatusResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_membuss_proto_init() }
func file_membuss_proto_init() {
	if File_membuss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membuss_proto_rawDesc), len(file_membuss_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_membuss_proto_goTypes,
		DependencyIndexes: file_membuss_proto_depIdxs,
		EnumInfos:         file_membuss_proto_enumTypes,
		MessageInfos:      file_membuss_proto_msgTypes,
	}.Build()
	File_membuss_proto = out.File
	file_membuss_proto_goTypes = nil
	file_membuss_proto_depIdxs = nil
}
