// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: memns.proto

package membusspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidityType int32

const (
	ValidityType_EOL ValidityType = 0 // expires at validity timestamp
)

// Enum value maps for ValidityType.
var (
	ValidityType_name = map[int32]string{
		0: "EOL",
	}
	ValidityType_value = map[string]int32{
		"EOL": 0,
	}
)

func (x ValidityType) Enum() *ValidityType {
	p := new(ValidityType)
	*p = x
	return p
}

func (x ValidityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidityType) Descriptor() protoreflect.EnumDescriptor {
	return file_memns_proto_enumTypes[0].Descriptor()
}

func (ValidityType) Type() protoreflect.EnumType {
	return &file_memns_proto_enumTypes[0]
}

func (x ValidityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidityType.Descriptor instead.
func (ValidityType) EnumDescriptor() ([]byte, []int) {
	return file_memns_proto_rawDescGZIP(), []int{0}
}

type MemRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        []byte                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`                                                                                   // MID or /mem/... path
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`                                                                                  // relative weight (0-100)
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`                                                                                     // e.g. "staging", "production", "canary"
	Conditions    map[string]string      `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. country, user-agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemRoute) Reset() {
	*x = MemRoute{}
	mi := &file_memns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemRoute) ProtoMessage() {}

func (x *MemRoute) ProtoReflect() protoreflect.Message {
	mi := &file_memns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemRoute.ProtoReflect.Descriptor instead.
func (*MemRoute) Descriptor() ([]byte, []int) {
	return file_memns_proto_rawDescGZIP(), []int{0}
}

func (x *MemRoute) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MemRoute) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *MemRoute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MemRoute) GetConditions() map[string]string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type MemLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // MID at that sequence
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // signed by key or delegate
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`     // optional human note e.g. "v2.1 release"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemLogEntry) Reset() {
	*x = MemLogEntry{}
	mi := &file_memns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemLogEntry) ProtoMessage() {}

func (x *MemLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_memns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemLogEntry.ProtoReflect.Descriptor instead.
func (*MemLogEntry) Descriptor() ([]byte, []int) {
	return file_memns_proto_rawDescGZIP(), []int{1}
}

func (x *MemLogEntry) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MemLogEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MemLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MemLogEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *MemLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MemLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemLogEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemLog) Reset() {
	*x = MemLog{}
	mi := &file_memns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemLog) ProtoMessage() {}

func (x *MemLog) ProtoReflect() protoreflect.Message {
	mi := &file_memns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemLog.ProtoReflect.Descriptor instead.
func (*MemLog) Descriptor() ([]byte, []int) {
	return file_memns_proto_rawDescGZIP(), []int{2}
}

func (x *MemLog) GetEntries() []*MemLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MemNSRecord struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Value        []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                          // target: MID or path e.g. /mem/mem1abc...
	Signature    []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // signature over value+sequence+validity
	Sequence     uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                   // monotonically increasing version number
	Validity     int64                  `protobuf:"varint,4,opt,name=validity,proto3" json:"validity,omitempty"`                   // unix ns expiry timestamp
	PublicKey    []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // signer's public key (for verification)
	Ttl          uint64                 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`                             // hint for caching (nanoseconds)
	ValidityType ValidityType           `protobuf:"varint,7,opt,name=validity_type,json=validityType,proto3,enum=membuss.v1.ValidityType" json:"validity_type,omitempty"`
	// Advanced features IPNS cannot do:
	Routes        []*MemRoute       `protobuf:"bytes,8,rep,name=routes,proto3" json:"routes,omitempty"`                                                                        // weighted multi-target routing
	Delegates     [][]byte          `protobuf:"bytes,9,rep,name=delegates,proto3" json:"delegates,omitempty"`                                                                  // delegated signer public keys
	Changelog     *MemLog           `protobuf:"bytes,10,opt,name=changelog,proto3" json:"changelog,omitempty"`                                                                 // signed history of changes
	Meta          map[string]string `protobuf:"bytes,11,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemNSRecord) Reset() {
	*x = MemNSRecord{}
	mi := &file_memns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemNSRecord) ProtoMessage() {}

func (x *MemNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_memns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemNSRecord.ProtoReflect.Descriptor instead.
func (*MemNSRecord) Descriptor() ([]byte, []int) {
	return file_memns_proto_rawDescGZIP(), []int{3}
}

func (x *MemNSRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MemNSRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *MemNSRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MemNSRecord) GetValidity() int64 {
	if x != nil {
		return x.Validity
	}
	return 0
}

func (x *MemNSRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MemNSRecord) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MemNSRecord) GetValidityType() ValidityType {
	if x != nil {
		return x.ValidityType
	}
	return ValidityType_EOL
}

func (x *MemNSRecord) GetRoutes() []*MemRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *MemNSRecord) GetDelegates() [][]byte {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *MemNSRecord) GetChangelog() *MemLog {
	if x != nil {
		return x.Changelog
	}
	return nil
}

func (x *MemNSRecord) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_memns_proto protoreflect.FileDescriptor

const file_memns_proto_rawDesc = "" +
	"\n" +
	"\vmemns.proto\x12\n" +
	"membuss.v1\"\xd5\x01\n" +
	"\bMemRoute\x12\x16\n" +
	"\x06target\x18\x01 \x01(\fR\x06target\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12D\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2$.membuss.v1.MemRoute.ConditionsEntryR\n" +
	"conditions\x1a=\n" +
	"\x0fConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\vMemLogEntry\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\";\n" +
	"\x06MemLog\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.membuss.v1.MemLogEntryR\aentries\"\xd7\x03\n" +
	"\vMemNSRecord\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1a\n" +
	"\bvalidity\x18\x04 \x01(\x03R\bvalidity\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x04R\x03ttl\x12=\n" +
	"\rvalidity_type\x18\a \x01(\x0e2\x18.membuss.v1.ValidityTypeR\fvalidityType\x12,\n" +
	"\x06routes\x18\b \x03(\v2\x14.membuss.v1.MemRouteR\x06routes\x12\x1c\n" +
	"\tdelegates\x18\t \x03(\fR\tdelegates\x120\n" +
	"\tchangelog\x18\n" +
	" \x01(\v2\x12.membuss.v1.MemLogR\tchangelog\x125\n" +
	"\x04meta\x18\v \x03(\v2!.membuss.v1.MemNSRecord.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x17\n" +
	"\fValidityType\x12\a\n" +
	"\x03EOL\x10\x00B.Z,github.com/nnlgsakib/membuss/proto;membusspbb\x06proto3"

var (
	file_memns_proto_rawDescOnce sync.Once
	file_memns_proto_rawDescData []byte
)

func file_memns_proto_rawDescGZIP() []byte {
	file_memns_proto_rawDescOnce.Do(func() {
		file_memns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memns_proto_rawDesc), len(file_memns_proto_rawDesc)))
	})
	return file_memns_proto_rawDescData
}

var file_memns_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_memns_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_memns_proto_goTypes = []any{
	(ValidityType)(0),   // 0: membuss.v1.ValidityType
	(*MemRoute)(nil),    // 1: membuss.v1.MemRoute
	(*MemLogEntry)(nil), // 2: membuss.v1.MemLogEntry
	(*MemLog)(nil),      // 3: membuss.v1.MemLog
	(*MemNSRecord)(nil), // 4: membuss.v1.MemNSRecord
	nil,                 // 5: membuss.v1.MemRoute.ConditionsEntry
	nil,                 // 6: membuss.v1.MemNSRecord.MetaEntry
}
var file_memns_proto_depIdxs = []int32{
	5, // 0: membuss.v1.MemRoute.conditions:type_name -> membuss.v1.MemRoute.ConditionsEntry
	2, // 1: membuss.v1.MemLog.entries:type_name -> membuss.v1.MemLogEntry
	0, // 2: membuss.v1.MemNSRecord.validity_type:type_name -> membuss.v1.ValidityType
	1, // 3: membuss.v1.MemNSRecord.routes:type_name -> membuss.v1.MemRoute
	3, // 4: membuss.v1.MemNSRecord.changelog:type_name -> membuss.v1.MemLog
	6, // 5: membuss.v1.MemNSRecord.meta:type_name -> membuss.v1.MemNSRecord.MetaEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_memns_proto_init() }
func file_memns_proto_init() {
	if File_memns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memns_proto_rawDesc), len(file_memns_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_memns_proto_goTypes,
		DependencyIndexes: file_memns_proto_depIdxs,
		EnumInfos:         file_memns_proto_enumTypes,
		MessageInfos:      file_memns_proto_msgTypes,
	}.Build()
	File_memns_proto = out.File
	file_memns_proto_goTypes = nil
	file_memns_proto_depIdxs = nil
}
