// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckExplorer() {
  return window['go']['main']['App']['CheckExplorer']();
}

export function CheckNodeStatus() {
  return window['go']['main']['App']['CheckNodeStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDaemonLogs() {
  return window['go']['main']['App']['GetDaemonLogs']();
}

export function GetNodeConfig() {
  return window['go']['main']['App']['GetNodeConfig']();
}

export function GetNodeConfigRaw() {
  return window['go']['main']['App']['GetNodeConfigRaw']();
}

export function InstallBinaries(arg1) {
  return window['go']['main']['App']['InstallBinaries'](arg1);
}

export function ResetSetup() {
  return window['go']['main']['App']['ResetSetup']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveNodeConfig(arg1) {
  return window['go']['main']['App']['SaveNodeConfig'](arg1);
}

export function SaveNodeConfigRaw(arg1) {
  return window['go']['main']['App']['SaveNodeConfigRaw'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartNode() {
  return window['go']['main']['App']['StartNode']();
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}

export function VerifyInstallation() {
  return window['go']['main']['App']['VerifyInstallation']();
}

export function WriteDefaultConfig() {
  return window['go']['main']['App']['WriteDefaultConfig']();
}
